--------------------
Failed to process https://github.com/rama213/webapp.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/rama213/webapp.git.
--------------------
Failed to process https://github.com/shaaandi/advancednodejs_ci.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:9240', '--from', 'c71e90def632b9eb0b3333aef922dde1f9bc04f3', '--to', 'b00e218b0afe133b5ab101ea6d1a38a2d2c923f6', '--git-dir', '/tmp/top-repos-quality-repos-nc9myoa5/advancednodejs_ci.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/learn-co-students/js-basics-strings-code-along-atlanta-web-033020.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:9240', '--from', '0470dc5012149b434ed14a9c2ca7ca4c2fb86691', '--to', '421b51742fba64f97e1e714d643e6f0a2454ea04', '--git-dir', '/tmp/top-repos-quality-repos-6g68wxn6/js-basics-strings-code-along-atlanta-web-033020.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/olejiksa/crossword-creator-web.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/olejiksa/crossword-creator-web.git.
